<a href="https://colab.research.google.com/github/dtermite/PythonColab/blob/main/Python_Data_Science_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color=green> PYTHON PARA DATA SCIENCE - NUMPY
---

# <font color=green> 1. INTRODUCCIÓN A PYTHON
---

# 1.1 Introducción

> Python es un lenguaje de programación de alto nivel con soporte a múltiples paradigmas de programación. Es un proyecto *open source* y desde su surgimiento, en 1991, viene convirtiéndose en uno de los lenguajes de programación interpretados más populares. 
>
> En los últimos años Python desarrolló una comunidad activa de procesamiento científico y análisis de datos y viene destacándose como uno de los lenguajes más relevantes cuando el asunto es ciencia de datos y machine learning, tanto en el entorno acadêmico como también en el entorno laboral.

# 1.2 Instalación y entorno de trabajo

### Instalación Local

### https://www.python.org/downloads/
### o
### https://www.anaconda.com/distribution/

### Google Colaboratory

### https://colab.research.google.com

### Verificando versión

In [ ]:
!python -V

Python 3.9.16


# 1.3 Trabajando con Numpy

In [ ]:
import numpy as np

In [ ]:
km =np.loadtxt('carros-km.txt', dtype = int)

FileNotFoundError: ignored

In [ ]:
km

array([1000, 2300, 4987, 1500])

In [ ]:
años =np.loadtxt('carros-años.txt', dtype = int)

In [ ]:
años

### Obtener el promedio de kilometros recorridos por año

In [ ]:
km_promedio = km / (2023-años)

In [ ]:
km_promedio

In [ ]:
type(km_promedio)

# <font color=green> 2. CARACTERÍSTICAS BÁSICAS DEL LENGUAJE
---

# 2.1 Operaciones matemáticas

### Operadores aritméticos: $+$, $-$, $*$, $/$, $**$, $\%$, $//$

### Suma ($+$)

In [ ]:
2+2

### Resta ($-$)

In [ ]:
2 - 2

### Multiplicación ($*$)

In [ ]:
2 * 3

### División ($/$) y ($//$)
La operación división siempre devuelve un número con punto decimal

In [ ]:
10 / 3

In [ ]:
10 // 3

### Exponenciación ($**$)

In [ ]:
2 ** 3

### Resto de la división ($\%$)

In [ ]:
10 % 3

In [ ]:
10 % 2

### Expresiones matemáticas

In [ ]:
5 * 2 + 3 * 2

In [ ]:
(5 * 2) + (3 * 2)

In [ ]:
5 * (2 + 3) * 2

### La variable _

En el modo interactivo, el último resultado impreso en pantalla es atribuído a la variable _

In [ ]:
5 * 2

In [ ]:
_ + 3 * 2

In [ ]:
_ / 2

# 2.2 Variables

### Nombres de variables

- Nombres de variables pueden comenzar con letras (a - z, A - Z) o con el símbolo *underscore* (_):

    > Altura
    >
    > _peso
    
- El resto del nombre puede contener letras, números o el símbolo "_":

    > nombre_de_variable
    >
    > _valor
    >
    > dia_28_11_
    

- Los nombres son *case sensitive*:

    > Nombre_De_Variable $\ne$ nombre_de_variable $\ne$ NOMBRE_DE_VARIABLE
    
### <font color=red>Observaciones:
- Existen algumas palabras reservadas del lenguaje que no pueden ser utilizadas como nombres de variables:

| |Lista de palabras <br>reservadas en Python| |
|:-------------:|:------------:|:-------------:|
| and           | as           | not           | 
| assert        | finally      | or            | 
| break         | for          | pass          | 
| class         | from         | nonlocal      | 
| continue      | global       | raise         | 
| def           | if           | return        | 
| del           | import       | try           | 
| elif          | in           | while         | 
| else          | is           | with          | 
| except        | lambda       | yield         | 
| False         | True         | None          | 

### Declaración de variables

### Operadores de asignación: $=$, $+=$, $-=$, $*=$, $/=$, $**=$, $\%=$, $//=$

In [ ]:
año_actual = 2022
año_fabricacion = 2003
km_total = 44410.0

In [ ]:
año_actual

In [ ]:
año_fabricacion

In [ ]:
km_total

# $$km_{promedio} = \frac {km_{total}}{(Año_{actual} - Año_{fabricación})}$$

### Operaciones con variables

In [ ]:
km_promedio = km_total / (año_actual - año_fabricacion)
km_promedio

In [ ]:
año_actual = 2022
año_fabricacion = 2003
km_total = 44410.0
km_promedio = km_total / (año_actual - año_fabricacion)
km_promedio

In [ ]:
año_actual = 2020
año_fabricacion = 2003
km_total = 44410.0
km_promedio = km_total / (año_actual - año_fabricacion)

km_total= km_total + km_promedio
km_total

In [ ]:
año_actual = 2020
año_fabricacion = 2003
km_total = 44410.0
km_promedio = km_total / (año_actual - año_fabricacion)

km_total +=  km_promedio
km_total

### Conclusión:
```
"valor = valor + 1" es equivalente a "valor += 1"
```

### Declaración múltiple

In [ ]:
año_actual, año_fabricacion, km_total = 2020, 2003, 44410.0

In [ ]:
año_actual

In [ ]:
año_fabricacion

In [ ]:
km_total

# 2.3 Tipos de datos

Los tipos de datos especifican como números y caracteres estarán guardados y manipulados dentro de un programa. Los tipos de datos básicos en Python son:

1. **Números**
    1. ***int*** - Enteros
    - ***float*** - Decimales
- **Booleanos** - Contiene valores True o False. Esencial cuando comenzamos a trabajar con declaraciones condicionales
- ***Strings*** - Secuencia de uno o más caracteres que puede incluir letras, números y otros tipos de caracteres. Representa un texto.
- **None** - Representa la ausencia de valor

### Números

In [ ]:
año_actual = 2020

In [ ]:
type(año_actual)

In [ ]:
km_total = 44410.0

In [ ]:
type(km_total)

### Booleanos

In [ ]:
zero_km = True

In [ ]:
type(zero_km)

In [ ]:
zero_km = False

In [ ]:
type(zero_km)

### Strings

In [ ]:
nombre = 'Jetta variant'
nombre

In [ ]:
nombre ="Jetta variant"
nombre

In [ ]:
nombre ='Jetta "variant"'
nombre

In [ ]:
nombre ="Jetta 'variant'"
nombre

In [ ]:
carro ='''
  nombre
  edad
  nota
'''

In [ ]:
type(carro)

In [ ]:
carro

### None

In [ ]:
kilometraje = None
kilometraje

In [ ]:
type(kilometraje)

# 2.4 Conversión de tipos

In [ ]:
a =10
b = 20
c = 'Python es '
d ='genial'

In [ ]:
type(a)

In [ ]:
type(b)

In [ ]:
type(c)

In [ ]:
type(d)

In [ ]:
a + b

In [ ]:
c + d

In [ ]:
c + a

### Conversiones de tipo

Funciones int(), float(), str()

In [ ]:
str(a)

In [ ]:
type(str(a))

In [ ]:
c + str(a)

In [ ]:
float(a)

In [ ]:
var = 3.141592

In [ ]:
int(var)

In [ ]:
var =3.99

In [ ]:
int(var)

# 2.5 Indentación, comentarios y formatación de *strings*

### Indentación

En el lenguaje Python los programas son estructurados por medio de indentación. En cualquier lenguaje de programación la práctica de colocar indentación es bastante útil, facilitando la lectura y también el mantenimiento del código. En Python la indentación no es solamente una cuestión de organización y estilo, sino que es un requisito del lenguaje.

In [ ]:
año_actual = 2020
año_fabricacion = 2020

if (año_actual == año_fabricacion):
    print('Verdadero')
else:
    print('Falso')

### Comentarios

Comentarios son extremamente importantes en un programa. Consiste en un texto que describe lo que el programa o una parte específica del programa está haciendo. Los comentarios son ignorados por el interpretador Python. 

Podemos tener comentarios de una única linea o de múltiples líneas.

In [ ]:
# Esto es un comentario
año_actual = 2020
año_actual

In [ ]:
# Esto
# es un 
# comentario
año_actual = 2020
año_actual

In [ ]:
'''Esto es un
comentario'''
año_actual = 2020
año_actual

In [ ]:
# Definiendo variables
año_actual = 2020
año_fabricacion = 2020

'''
Estructura condicional que vamos 
a aprender la próxima clase
'''
if (año_actual == año_fabricacion):   # Probando si la condición es verdadera
    print('Verdadero')
else:                               # Probando si la condición es falsa
    print('Falso')

### Formatación de *strings*

## *str.format()*

https://docs.python.org/3.6/library/stdtypes.html#str.format

In [ ]:
print('Hola, {}'.format('Alejandro'))

In [ ]:
print('Hola, {}! Esta es su visita numero {}'.format('Alejandro',32))

In [ ]:
print('Hola, {}! Esta es su visita numero {}'.format(32,'Alejandro'))
print('Hola, {nombre}! Esta es su visita numero {años}'.format(nombre='Alejandro',años=32))

## *f-Strings*

https://docs.python.org/3.6/reference/lexical_analysis.html#f-strings

In [ ]:
nombre='Alejandro'
años=32
print(f'Hola, {nombre}! Esta es su visita numero {años}')

# <font color=green> 3. TRABAJANDO CON LISTAS
---

# 3.1 Creando listas

Listas son secuencias **mutables** que son utilizadas para guardar colecciones de objetos, generalmente homogéneos. Pueden ser construídas de varias formas:
```
- Utilizando un par de corchetes: [ ], [ 1 ]
- Utilizando un par de corchetes con objetos separados por comas: [ 1, 2, 3 ]
```

In [ ]:
Accesorios = ['Cerraduras eléctricas', 'Piloto automático', 'Asientos de cuero', 'Aire acondicionado', 'Sensor de estacionamiento', 'Sensor de lluvia']
Accesorios

In [ ]:
type(Accesorios)

### Lista con tipos de datos variados

In [ ]:
Carro_1 = ['Jetta Variant', 'Motor 4.0 Turbo', 2003, 44410.0, False, ['Cerraduras eléctricas', 'Piloto automático'], 88078.64]
Carro_2 = ['Passat', 'Motor Diesel', 1991, 5712.0, False, ['Central multimedia', 'Frenos ABS'], 106161.94]

In [ ]:
Carro_1

In [ ]:
Carro_2

In [ ]:
carros =[Carro_1, Carro_2]
carros

# 3.2 Operaciones con listas

https://docs.python.org/3.6/library/stdtypes.html#common-sequence-operations

## *x in A*

Devuelve **True** si un elemento de la lista *A es igual a x*.

In [ ]:
Accesorios

In [ ]:
'Cerraduras eléctricas' in Accesorios

In [ ]:
'4 x 4' in Accesorios 

In [ ]:
'4 x 4' not in Accesorios

## *A + B*

Concatena las listas *A y B*.

In [ ]:
A = ['Cerraduras eléctricas', 'Piloto automático', 'Asientos de cuero']
B = ['Aire acondicionado', 'Sensor de estacionamiento', 'Sensor de lluvia']

In [ ]:
A + B

## *len(A)*

Tamaño de la lista A.

In [ ]:
len(A)
len(B)
len(A+B)

In [ ]:
carro = [
'Jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Llantas de aleación', 'Cerraduras eléctricas', 'Piloto automático'],
 88078.64
]

#'2003' in carro

#'Llantas de aleación' in carro

'False' not in carro

# 3.3 Selecciones en listas

## *A[ n ]*

Devuelve el n-ésimo objeto de la lista *A*.

<font color=red>**Observación:**</font> Listas tienen indexación con inicio en cero.

In [ ]:
Accesorios

In [ ]:
Accesorios[0]

In [ ]:
Accesorios[1]

In [ ]:
Accesorios[-1]

In [ ]:
carros

In [ ]:
carros[0]

In [ ]:
carros[0][0]

In [ ]:
carros[0][-2]

In [ ]:
carros[0][-2][1]

## *A[ i : j ]*

Recorta la lista A desde el índice i hasta j. En este recorte el elemento con índice i **es incluído** y el elemento con índice j **no es incluído** en el resultado.

In [ ]:
Accesorios

In [ ]:
Accesorios[2:5]

In [ ]:
Accesorios[2:6]

In [ ]:
Accesorios[2:]

In [ ]:
Accesorios[:5]

In [ ]:
carros = [
    [
        'Jetta Variant',
        'Motor 4.0 Turbo',
        2003,
        False,
        ['Llantas de aleación', 'Cerraduras eléctricas', 'Piloto automático']
    ],
    [
        'Passat',
        'Motor Diesel',
        1991,
        True,
        ['Central multimedia', 'Techo panorámico', 'Frenos ABS']
    ]
]

In [ ]:
carros

In [ ]:
#carros[1][3] 
#carros[1][-1][-2]
carros[0][-1]

# 3.4 Métodos en listas

https://docs.python.org/3.6/library/stdtypes.html#mutable-sequence-types

## *A.sort()*

Ordena la lista *A*.

In [ ]:
Accesorios

In [ ]:
Accesorios.sort()
Accesorios

## *A.append(x)*

Añade el elemento *x al final de la lista A*

In [ ]:
Accesorios.append('4 x 4')
Accesorios

## *A.pop(i)*

Elimina y devuelve el elemento de índice i de la lista *A*.

<font color=red>**Observación:**</font> Por *defecto* el método *pop()* elimina y devuelve el último elemento de una lista.

In [ ]:
Accesorios.pop()
Accesorios

In [ ]:
Accesorios.pop(3)

In [ ]:
Accesorios

## *A.copy()*

Crea una copia de la lista *A*.

<font color=red>**Observación:**</font> El mismo resultado puede ser obtenido con el seguinte código: 
```
A[:]
```

In [ ]:
Accesorios_2 = Accesorios
Accesorios_2

In [ ]:
Accesorios_2.append('4 x 4')
Accesorios_2

In [ ]:
Accesorios

In [ ]:
Accesorios.pop()

In [ ]:
Accesorios

In [ ]:
Accesorios_2

In [ ]:
Accesorios_2 = Accesorios.copy()

In [ ]:
Accesorios_2

In [ ]:
Accesorios_2.append('4 x 4')

In [ ]:
Accesorios

In [ ]:
Accesorios_2

In [ ]:
Accesorios_2 = Accesorios[:]
Accesorios_2

# <font color=green> 4. ESTRUCTURAS DE REPETICIÓN Y CONDICIONALES
---

# 4.1 Instrucción *for*

#### Formato estándar

```
for <variable> in <coleccion>:
    <instrucciones>
```

### Loops con listas

In [ ]:
for item in Accesorios:
  print(item)


###  List comprehensions

https://docs.python.org/3.6/tutorial/datastructures.html#list-comprehensions

*range()* -> https://docs.python.org/3.6/library/functions.html#func-range

In [ ]:
range(10)

range(0, 10)

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
for i in range(10):
  print(i ** 2)

0
1
4
9
16
25
36
49
64
81


In [ ]:
cuadrado = []
for i in range(10):
  cuadrado.append(i ** 2)

cuadrado

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [ ]:
cuadrado = [i ** 2 for i in range(10)]

In [ ]:
cuadrado

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

# 4.2 Loops anidados

In [ ]:
datos = [ 
    ['Llantas de aleación', 'Cerraduras eléctricas', 'Piloto automático', 'Asientos de cuero', 'Aire acondicionado', 'Sensor de estacionamiento', 'Sensor de crepúsculo', 'Sensor de lluvia'],
    ['Central multimedia', 'Techo panorámico', 'Frenos ABS', '4 X 4', 'Panel digital', 'Piloto automático', 'Asientos de cuero', 'Cámara de estacionamiento'],
    ['Piloto automático', 'Control de estabilidad', 'Sensor crepuscular', 'Frenos ABS', 'Transmisión automática', 'Asientos de cuero', 'Central multimedia', 'Ventanas eléctricas']
]
datos

[['Llantas de aleación',
  'Cerraduras eléctricas',
  'Piloto automático',
  'Asientos de cuero',
  'Aire acondicionado',
  'Sensor de estacionamiento',
  'Sensor de crepúsculo',
  'Sensor de lluvia'],
 ['Central multimedia',
  'Techo panorámico',
  'Frenos ABS',
  '4 X 4',
  'Panel digital',
  'Piloto automático',
  'Asientos de cuero',
  'Cámara de estacionamiento'],
 ['Piloto automático',
  'Control de estabilidad',
  'Sensor crepuscular',
  'Frenos ABS',
  'Transmisión automática',
  'Asientos de cuero',
  'Central multimedia',
  'Ventanas eléctricas']]

In [ ]:
for lista in datos:
  print(lista)

['Llantas de aleación', 'Cerraduras eléctricas', 'Piloto automático', 'Asientos de cuero', 'Aire acondicionado', 'Sensor de estacionamiento', 'Sensor de crepúsculo', 'Sensor de lluvia']
['Central multimedia', 'Techo panorámico', 'Frenos ABS', '4 X 4', 'Panel digital', 'Piloto automático', 'Asientos de cuero', 'Cámara de estacionamiento']
['Piloto automático', 'Control de estabilidad', 'Sensor crepuscular', 'Frenos ABS', 'Transmisión automática', 'Asientos de cuero', 'Central multimedia', 'Ventanas eléctricas']


In [ ]:
for lista in datos:
  for item in lista:
    print(item)


Llantas de aleación
Cerraduras eléctricas
Piloto automático
Asientos de cuero
Aire acondicionado
Sensor de estacionamiento
Sensor de crepúsculo
Sensor de lluvia
Central multimedia
Techo panorámico
Frenos ABS
4 X 4
Panel digital
Piloto automático
Asientos de cuero
Cámara de estacionamiento
Piloto automático
Control de estabilidad
Sensor crepuscular
Frenos ABS
Transmisión automática
Asientos de cuero
Central multimedia
Ventanas eléctricas


In [ ]:
Accesorios = []
for lista in datos:
  for item in lista:
    Accesorios.append(item)

Accesorios

['Llantas de aleación',
 'Cerraduras eléctricas',
 'Piloto automático',
 'Asientos de cuero',
 'Aire acondicionado',
 'Sensor de estacionamiento',
 'Sensor de crepúsculo',
 'Sensor de lluvia',
 'Central multimedia',
 'Techo panorámico',
 'Frenos ABS',
 '4 X 4',
 'Panel digital',
 'Piloto automático',
 'Asientos de cuero',
 'Cámara de estacionamiento',
 'Piloto automático',
 'Control de estabilidad',
 'Sensor crepuscular',
 'Frenos ABS',
 'Transmisión automática',
 'Asientos de cuero',
 'Central multimedia',
 'Ventanas eléctricas']

## *set()*

https://docs.python.org/3.6/library/stdtypes.html#types-set

https://docs.python.org/3.6/library/functions.html#func-set

In [ ]:
set(Accesorios)

{'4 X 4',
 'Aire acondicionado',
 'Asientos de cuero',
 'Central multimedia',
 'Cerraduras eléctricas',
 'Control de estabilidad',
 'Cámara de estacionamiento',
 'Frenos ABS',
 'Llantas de aleación',
 'Panel digital',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de crepúsculo',
 'Sensor de estacionamiento',
 'Sensor de lluvia',
 'Techo panorámico',
 'Transmisión automática',
 'Ventanas eléctricas'}

In [ ]:
list(set(Accesorios))

['Panel digital',
 'Techo panorámico',
 '4 X 4',
 'Llantas de aleación',
 'Frenos ABS',
 'Aire acondicionado',
 'Piloto automático',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Sensor de crepúsculo',
 'Sensor de lluvia',
 'Transmisión automática',
 'Central multimedia',
 'Ventanas eléctricas',
 'Sensor crepuscular',
 'Control de estabilidad',
 'Sensor de estacionamiento',
 'Cámara de estacionamiento']

### List comprehensions

In [ ]:
Accesorios = list(set([item for lista in datos for item in lista]))

In [ ]:
Accesorios

['Panel digital',
 'Techo panorámico',
 '4 X 4',
 'Llantas de aleación',
 'Frenos ABS',
 'Aire acondicionado',
 'Piloto automático',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Sensor de crepúsculo',
 'Sensor de lluvia',
 'Transmisión automática',
 'Central multimedia',
 'Ventanas eléctricas',
 'Sensor crepuscular',
 'Control de estabilidad',
 'Sensor de estacionamiento',
 'Cámara de estacionamiento']

# 4.3 Instrucción *if*

#### Formato estándar

```
if <condicion>:
     <instrucciones en caso la condición sea verdadera>
```

### Operadores de comparación: $==$, $!=$, $>$, $<$, $>=$, $<=$
### y
### Operadores lógicos: $and$, $or$, $not$

In [ ]:
# 1º objeto de la lista - Nombre del vehículo
# 2º objeto de la lista - Año de fabricación
# 3º objeto de la lista - Vehículo es cero km?

datos = [
    ['Jetta Variant', 2003, False],
    ['Passat', 1991, False],
    ['Crossfox', 1990, False],
    ['DS5', 2019, True],
    ['Aston Martin DB4', 2006, False],
    ['Palio Weekend', 2012, False],
    ['A5', 2019, True],
    ['Série 3 Cabrio', 2009, False],
    ['Dodge Jorney', 2019, False],
    ['Carens', 2011, False]
]
datos

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [ ]:
cero_km_T = []
for lista in datos:
  if (lista[2] == True):
    cero_km_T.append(lista)

cero_km_T

[['DS5', 2019, True], ['A5', 2019, True]]

In [ ]:
cero_km_F = []
for lista in datos:
  if (lista[2] == False):
    cero_km_F.append(lista)

cero_km_F

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

### List comprehensions

In [ ]:
[lista for lista in datos if(lista[2]== True)]

[['DS5', 2019, True], ['A5', 2019, True]]

# 4.4 Instrucciones *if-else* y *if-elif-else*

#### Formato estándar

```
if <condicion>:
    <instrucciones en caso la condición sea verdadera>
else:
    <instrucciones en caso la condición no sea verdadera>
```

In [ ]:
cero_km_T, cero_km_F = [], []

for lista in datos:
  if (lista[2] == True):
    cero_km_T.append(lista)
  else:
    cero_km_F.append(lista)



In [ ]:
cero_km_T

[['DS5', 2019, True], ['A5', 2019, True]]

In [ ]:
cero_km_F

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

#### Formato estándar

```
if <condicion 1>:
    <instrucciones en caso la condición 1 sea verdadera>
elif <condicion 2>:
    <instrucciones en caso la condición 2 sea verdadera>
elif <condicion 3>:
    <instrucciones en caso la condición 3 sea verdadera>
                        .
                        .
                        .
else:
    <instrucciones en caso las condiciones anteriores no sean verdaderas>
```

In [ ]:
datos

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [ ]:
print('AND')
print(f'(True and True) el resultado es: {True and True}')
print(f'(True and False) el resultado es: {True and False}')
print(f'(False and True) el resultado es: {False and True}')
print(f'(False and False) el resultado es: {False and False}')

AND
(True and True) el resultado es: True
(True and False) el resultado es: False
(False and True) el resultado es: False
(False and False) el resultado es: False


In [ ]:
print('OR')
print(f'(True or True) el resultado es: {True or True}')
print(f'(True or False) el resultado es: {True or False}')
print(f'(False or True) el resultado es: {False or True}')
print(f'(False or False) el resultado es: {False or False}')

OR
(True or True) el resultado es: True
(True or False) el resultado es: True
(False or True) el resultado es: True
(False or False) el resultado es: False


In [ ]:
A, B, C = [], [], []
for lista in datos:
  if (lista[1] <= 2000):
    A.append(lista)
  elif (lista[1]>2000 and lista[1]<=2010):
    B.append(lista)
  else:
    C.append(lista)

In [ ]:
A

[['Passat', 1991, False], ['Crossfox', 1990, False]]

In [ ]:
B

[['Jetta Variant', 2003, False],
 ['Aston Martin DB4', 2006, False],
 ['Série 3 Cabrio', 2009, False]]

In [ ]:
C

[['DS5', 2019, True],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [ ]:
A, B, C = [], [], []
for lista in datos:
  if (lista[1] <= 2000):
    A.append(lista)
  elif (2000 < lista[1] <=2010):
    B.append(lista)
  else:
    C.append(lista)

# <font color=green> 5. NUMPY BÁSICO
---

Numpy es la abreviación de Numerical Python y es uno de los paquetes más importantes para procesamiento numérico en Python. Numpy ofrece la base para la mayoría de los paquetes de aplicaciones científicas que usen datos numéricos en Python (estructuras de datos y algoritmos). Pueden destacarse los siguientes recursos que el paquete Numpy contiene:

- Un poderoso objeto array multidimensional;
- Funciones matemáticas sofisticadas para operaciones con arrays sin la necesidad de utilización de bucles *for*;
- Recursos de algebra linear y generación de números aleatórios

Además de sus obvios usos científicos, el paquete NumPy también es muy utilizado en análisis de datos como un eficiente contenedor multidimensional de datos genéricos para transporte entre diversos algoritmos y bibliotecas en Python.

**Versión:** 1.18.4

**Instalación:** https://scipy.org/install.html

**Documentación:** https://numpy.org/doc/1.18/

### Paquetes

Existen diversos paquetes Python disponibles para download en internet. Cada paquete tiene como objetivo la solución de determinado tipo de problema y para esto son desarrollados nuevos tipos, funciones y métodos.

Algunos paquetes son bastante utilizados en un contexto de ciencia de datos, como por ejemplo:

- Numpy
- Pandas
- Scikit-learn
- Matplotlib

Algunos paquetes no son distribuidos en la instalación estándar de Python. En este caso debemos instalar los paquetes que necesitamos en nuestro sistema para poder utilizar sus funcionalidades.

### Importando todo el paquete

In [ ]:
import numpy

https://numpy.org/doc/1.16/reference/generated/numpy.arange.html

In [ ]:
numpy.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando todo el paquete y asignándole un nuevo nombre 

In [ ]:
import numpy as np

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando parte del paquete

In [ ]:
from numpy import arange

In [ ]:
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 5.1 Creando arrays Numpy

In [1]:
import numpy as np

### A partir de listas

https://numpy.org/doc/1.16/user/basics.creation.html

In [2]:
km = np.array([1000, 2300, 4987, 1500])

In [3]:
km

array([1000, 2300, 4987, 1500])

In [4]:
type(km)

numpy.ndarray

https://numpy.org/doc/1.16/user/basics.types.html

In [5]:
km.dtype

dtype('int64')

### A partir de datos externos

https://numpy.org/doc/1.16/reference/generated/numpy.loadtxt.html

In [7]:
km = np.loadtxt(fname='carros-km.txt', dtype = int)

In [8]:
km

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [9]:
km.dtype

dtype('int64')

### Arrays con dos dimensiones

In [10]:
datos = [ 
    ['Llantas de aleación', 'Cerraduras eléctricas', 'Piloto automático', 'Asientos de cuero', 'Aire acondicionado', 'Sensor de estacionamiento', 'Sensor de crepúsculo', 'Sensor de lluvia'],
    ['Central multimedia', 'Techo panorámico', 'Frenos ABS', '4 X 4', 'Panel digital', 'Piloto automático', 'Asientos de cuero', 'Cámara de estacionamiento'],
    ['Piloto automático', 'Control de estabilidad', 'Sensor crepuscular', 'Frenos ABS', 'Transmisión automática', 'Asientos de cuero', 'Central multimedia', 'Ventanas eléctricas']
]
datos

[['Llantas de aleación',
  'Cerraduras eléctricas',
  'Piloto automático',
  'Asientos de cuero',
  'Aire acondicionado',
  'Sensor de estacionamiento',
  'Sensor de crepúsculo',
  'Sensor de lluvia'],
 ['Central multimedia',
  'Techo panorámico',
  'Frenos ABS',
  '4 X 4',
  'Panel digital',
  'Piloto automático',
  'Asientos de cuero',
  'Cámara de estacionamiento'],
 ['Piloto automático',
  'Control de estabilidad',
  'Sensor crepuscular',
  'Frenos ABS',
  'Transmisión automática',
  'Asientos de cuero',
  'Central multimedia',
  'Ventanas eléctricas']]

In [11]:
Accesorios = np.array(datos)

In [12]:
Accesorios

array([['Llantas de aleación', 'Cerraduras eléctricas',
        'Piloto automático', 'Asientos de cuero', 'Aire acondicionado',
        'Sensor de estacionamiento', 'Sensor de crepúsculo',
        'Sensor de lluvia'],
       ['Central multimedia', 'Techo panorámico', 'Frenos ABS', '4 X 4',
        'Panel digital', 'Piloto automático', 'Asientos de cuero',
        'Cámara de estacionamiento'],
       ['Piloto automático', 'Control de estabilidad',
        'Sensor crepuscular', 'Frenos ABS', 'Transmisión automática',
        'Asientos de cuero', 'Central multimedia', 'Ventanas eléctricas']],
      dtype='<U25')

In [13]:
km.shape

(258,)

In [14]:
Accesorios.shape

(3, 8)

### Comparando desempeño con listas

In [15]:
np_array = np.arange(1000000)

In [16]:
py_list = list(range(1000000))

In [17]:
%time for _ in range(100): np_array *= 2

CPU times: user 35.8 ms, sys: 931 µs, total: 36.8 ms
Wall time: 36.1 ms


In [18]:
%time for _ in range(100): py_list = [x*2 for x in py_list]

CPU times: user 5.29 s, sys: 1.3 s, total: 6.6 s
Wall time: 6.61 s


# 5.2 Operaciones aritméticas con arrays Numpy

### Operaciones entre arrays y constantes

In [19]:
import numpy as np
km = [44410., 5712., 37123., 0., 25757.]
años = [2003, 1991, 1990, 2019, 2006]

In [20]:
edad = 2020 - años

TypeError: ignored

In [21]:
km = np.array([44410., 5712., 37123., 0., 25757.])
años = np.array([2003, 1991, 1990, 2019, 2006])

In [22]:
edad = 2020 - años

In [23]:
edad

array([17, 29, 30,  1, 14])

### Operaciones entre arrays

In [ ]:
km_media = km / edad

In [ ]:
km_media

array([2612.35294118,  196.96551724, 1237.43333333,    0.        ,
       1839.78571429])

In [ ]:
44410. / 17

2612.3529411764707

### Operaciones con arrays de dos dimensiones

In [38]:
datos = np.array([km, años])

In [39]:
datos

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
datos.shape

(2, 5)

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [ ]:
datos[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [ ]:
datos[1]

array([2003., 1991., 1990., 2019., 2006.])

In [ ]:
km_media = datos[0] / (2020 - datos[1])
km_media

array([2612.35294118,  196.96551724, 1237.43333333,    0.        ,
       1839.78571429])

# 5.3 Selecciones con arrays Numpy

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [37]:
datos

[['Llantas de aleación',
  'Cerraduras eléctricas',
  'Piloto automático',
  'Asientos de cuero',
  'Aire acondicionado',
  'Sensor de estacionamiento',
  'Sensor de crepúsculo',
  'Sensor de lluvia'],
 ['Central multimedia',
  'Techo panorámico',
  'Frenos ABS',
  '4 X 4',
  'Panel digital',
  'Piloto automático',
  'Asientos de cuero',
  'Cámara de estacionamiento'],
 ['Piloto automático',
  'Control de estabilidad',
  'Sensor crepuscular',
  'Frenos ABS',
  'Transmisión automática',
  'Asientos de cuero',
  'Central multimedia',
  'Ventanas eléctricas']]

![1410-img02.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img02.png)

### Indexación 

<font color=red>**Observación:**</font> La indexación tiene inicio en cero.

In [ ]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
contador[0]

0

In [ ]:
contador[9]

9

In [ ]:
contador[-1]

9

In [ ]:
datos[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [ ]:
datos[1]

array([2003., 1991., 1990., 2019., 2006.])

## <font color=green>**Consejo:**</font>
### *ndarray[ linea ][ columna ]* o *ndarray[ linea, columna ]*

In [ ]:
datos[1][2]

1990.0

In [ ]:
datos[1, 2]

1990.0

 ### Particiones
 
La sintaxis para realizar particiones en un array Numpy es $i : j : k$ donde $i$ es el índice inicial, $j$ es el índice final, y $k$ es el indicador de intervalo ($k\neq0$)
 
<font color=red>**Observación:**</font> En las particiones (*slices*) el objeto con índice i es **incluído** y el objeto con índice j **no es incluído** en el resultado.

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [30]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
contador[1:4:]

array([1, 2, 3])

In [32]:
contador[1:8:2]

array([1, 3, 5, 7])

In [33]:
contador[::2]

array([0, 2, 4, 6, 8])

In [34]:
contador[1::2]

array([1, 3, 5, 7, 9])

In [35]:
datos

[['Llantas de aleación',
  'Cerraduras eléctricas',
  'Piloto automático',
  'Asientos de cuero',
  'Aire acondicionado',
  'Sensor de estacionamiento',
  'Sensor de crepúsculo',
  'Sensor de lluvia'],
 ['Central multimedia',
  'Techo panorámico',
  'Frenos ABS',
  '4 X 4',
  'Panel digital',
  'Piloto automático',
  'Asientos de cuero',
  'Cámara de estacionamiento'],
 ['Piloto automático',
  'Control de estabilidad',
  'Sensor crepuscular',
  'Frenos ABS',
  'Transmisión automática',
  'Asientos de cuero',
  'Central multimedia',
  'Ventanas eléctricas']]

In [36]:
datos[::,1:3:]

TypeError: ignored

In [27]:
datos[::,1:3:][0] / (2020 - datos[::, 1:3:][1])

TypeError: ignored

In [ ]:
datos[0] / (2020- datos[1])

array([2612.35294118,  196.96551724, 1237.43333333,    0.        ,
       1839.78571429])

### Indexación con array booleano

<font color=red>**Observación:**</font> Selecciona un grupo de líneas y columnas siguiendo las etiquetas o un array booleano.

In [ ]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
contador >  5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [ ]:
contador[contador > 5]

array([6, 7, 8, 9])

In [ ]:
datos[1] > 2000

array([ True, False, False,  True,  True])

In [ ]:
datos[::, datos[1]>2000]

array([[44410.,     0., 25757.],
       [ 2003.,  2019.,  2006.]])

# 5.4 Atributos y métodos de arrays Numpy

### Atributos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-attributes

In [40]:
datos

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

## *ndarray.shape*

Devuelve una tupla con las dimensiones del array.

In [42]:
datos.shape

(2, 5)

## *ndarray.ndim*

Devuelve el número de dimensiones del array.

In [43]:
datos.ndim

2

## *ndarray.size*

Devuelve el número de elementos del array.

In [44]:
datos.size

10

## *ndarray.dtype*

Devuelve el tipo de datos de los elementos del array.

In [45]:
datos.dtype

dtype('float64')

## *ndarray.T*

Devuelve el array transpuesto, es decir, convierte líneas en columnas y viceversa.

In [46]:
datos.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [48]:
datos.transpose()

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

### Métodos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-methods

## *ndarray.tolist()*

Devuelve el array como una lista Python.

In [49]:
datos.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

## *ndarray.reshape(shape[, order])*

Devuelve un array que contiene los mismos datos con una nueva forma.

In [50]:
contador =np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
filas = 5
columnas= 2
contador.reshape(filas, columnas)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [52]:
contador.reshape(filas, columnas, order ='C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [53]:
contador.reshape(filas, columnas, order ='F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [54]:
km = [44410, 5712, 37123, 0, 25757]
años = [2003, 1991, 1990, 2019, 2006]

In [55]:
info_carros = km + años
info_carros

[44410, 5712, 37123, 0, 25757, 2003, 1991, 1990, 2019, 2006]

In [58]:
np.array(info_carros).reshape(2, 5)

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [59]:
np.array(info_carros).reshape(5, 2, order='F')

array([[44410,  2003],
       [ 5712,  1991],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

## *ndarray.resize(new_shape[, refcheck])*

Cambia la forma y el tamaño del array.

In [60]:
datos_new = datos.copy()
datos_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [62]:
datos_new.resize((3, 5),refcheck=False)

In [63]:
datos_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

In [64]:
datos_new[2] = datos_new[0] / (2020 - datos_new[1])
datos_new

array([[44410.        ,  5712.        , 37123.        ,     0.        ,
        25757.        ],
       [ 2003.        ,  1991.        ,  1990.        ,  2019.        ,
         2006.        ],
       [ 2612.35294118,   196.96551724,  1237.43333333,     0.        ,
         1839.78571429]])

# 5.5 Estadísticas con arrays Numpy

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#calculation

y

https://numpy.org/doc/1.16/reference/routines.statistics.html

y

https://numpy.org/doc/1.16/reference/routines.math.html

In [65]:
años = np.loadtxt(fname = "carros-años.txt", dtype = int)
km = np.loadtxt(fname = "carros-km.txt")
valor = np.loadtxt(fname = "carros-valor.txt")

https://numpy.org/doc/1.16/reference/generated/numpy.column_stack.html

In [66]:
años.shape

(258,)

In [67]:
dataset = np.column_stack((años, km, valor))
dataset

array([[2.0030000e+03, 4.4410000e+04, 8.8078640e+04],
       [1.9910000e+03, 5.7120000e+03, 1.0616194e+05],
       [1.9900000e+03, 3.7123000e+04, 7.2832160e+04],
       [2.0200000e+03, 0.0000000e+00, 1.2454907e+05],
       [2.0060000e+03, 2.5757000e+04, 9.2612100e+04],
       [2.0120000e+03, 1.0728000e+04, 9.7497730e+04],
       [2.0200000e+03, 0.0000000e+00, 5.6445200e+04],
       [2.0090000e+03, 7.7599000e+04, 1.1231044e+05],
       [2.0100000e+03, 9.9197000e+04, 1.2071627e+05],
       [2.0110000e+03, 3.7978000e+04, 7.6566490e+04],
       [2.0020000e+03, 1.2859000e+04, 7.1647590e+04],
       [2.0070000e+03, 8.0520000e+03, 7.3919530e+04],
       [2.0010000e+03, 8.9773000e+04, 1.1273299e+05],
       [2.0200000e+03, 0.0000000e+00, 5.3183380e+04],
       [2.0090000e+03, 4.1457000e+04, 1.2748842e+05],
       [2.0160000e+03, 1.1560700e+05, 5.9910400e+04],
       [2.0120000e+03, 4.6449000e+04, 6.1118590e+04],
       [2.0200000e+03, 0.0000000e+00, 8.8552390e+04],
       [2.0160000e+03, 3.708

In [69]:
dataset.shape

(258, 3)

## *np.mean()*

Devuelve el promedio de los elementos del array a lo largo del eje especificado.

In [71]:
np.mean(dataset, axis=0)

array([ 2007.74806202, 44499.41472868, 98960.51310078])

In [72]:
np.mean(dataset, axis=1)

array([44830.54666667, 37954.98      , 37315.05333333, 42189.69      ,
       40125.03333333, 36745.91      , 19488.4       , 63972.81333333,
       73974.42333333, 38851.83      , 28836.19666667, 27992.84333333,
       68168.99666667, 18401.12666667, 56984.80666667, 59177.8       ,
       36526.53      , 30190.79666667, 33932.89666667, 39638.76666667,
       69780.79333333, 32194.8       , 77867.61333333, 76878.21666667,
       41205.40333333, 24462.36666667, 34386.25      , 35817.61333333,
       39298.42333333, 72268.23333333, 34289.06666667, 41477.39333333,
       26365.56333333, 33918.13333333, 50905.01      , 54959.84      ,
       17875.53      , 41767.29      , 25768.39333333, 34876.51333333,
       54475.06333333, 59333.43      , 29553.78      , 75040.79666667,
       39882.24333333, 22655.23333333, 52057.21666667, 31725.88333333,
       22240.36666667, 69567.49666667, 78571.96333333, 61600.27666667,
       69114.54333333, 58791.90333333, 31242.99666667, 51282.34333333,
      

In [73]:
np.mean(dataset[::, 1])

44499.41472868217

In [74]:
np.mean(dataset[::, 2])

98960.51310077519

## *np.std()*

Devuelve la desviación estándar de los elementos del array a lo largo del eje especificado.

In [75]:
np.std(dataset[::, 2])

29754.101150388564

## *ndarray.sum()*

Devuelve la suma de los elementos del array a lo largo del eje especificado.

In [76]:
dataset.sum(axis =0)

array([  517999.        , 11480849.        , 25531812.37999999])

In [78]:
dataset[::, 1].sum()

11480849.0

## *np.sum()*

Devuelve la suma de los elementos del array a lo largo del eje especificado.

In [77]:
np.sum(dataset, axis =0)

array([  517999.        , 11480849.        , 25531812.37999999])

In [79]:
np.sum(dataset[::, 2] )

25531812.38

In [80]:
import pandas as pd
df=pd.DataFrame(data=dataset, columns=["años", "km", "valor"])
result= df.groupby('años').mean()
print(result)

                  km          valor
años                               
1990.0  72083.666667   96116.206667
1991.0  47036.444444   93420.658889
1992.0  51283.000000   90670.667500
1993.0  55384.250000   93357.635000
1994.0  70260.777778   96623.326667
1995.0  71289.714286   86117.702857
1996.0  50926.100000   98619.528000
1997.0  71897.000000   96852.883333
1998.0  71828.000000   97801.913333
1999.0  39075.500000   98675.220000
2000.0  98921.000000  112101.906667
2001.0  69583.750000  105120.757500
2002.0  59268.545455   89327.512727
2003.0  56926.571429  111672.687143
2004.0  62735.800000   82253.320000
2005.0  58052.500000  117836.888333
2006.0  45569.750000   91200.577500
2007.0  59986.750000  101135.170000
2008.0  61647.833333  103123.380000
2009.0  48694.000000  110470.614286
2010.0  79227.333333   98001.035000
2011.0  53031.000000  106613.244000
2012.0  40817.500000   89212.192500
2013.0  39021.777778  105672.001111
2014.0  57461.500000   87228.613333
2015.0  61032.125000  103795